export const news = state => state.news
export const interfaceList = state => state.interfaceList
export const processList = state => state.processList
export const routerName = state => state.routerName
export const processUpload = state => state.processUpload
export const yizhangtongForm = state => state.yizhangtongForm
export const isCheckLeaseForm = state => state.isCheckLeaseForm
export const leaseId = state => state.leaseId
export const sessionData = state => state.sessionData
export const incomeList = state => state.incomeList
export const stateList = state => state.stateList
export const fileToUploadList = state => state.fileToUploadList
export const productDiff = state => state.productDiff
export const stateIndex = state => state.stateIndex
export const attachmentIndex = state => state.attachmentIndex
export const product = state => state.product
export const activeIndex = state => state.activeIndex
export const dics = state => state.dics
export const area = state => state.area